-- Header/shell asset strings for the rendered HTML.
-- Generated from GfmPreviewWithToc.py; do not hand-edit.

local M = {}

M.SIMPLE_HTML_START = '<div class="markdown-body" style="max-width:900px;margin:0 auto;padding:2rem;color-scheme:light dark">\n'
M.SIMPLE_HTML_END = '</div>'
M.dark_mode_style = '<style>:root{color-scheme:light dark}@media(prefers-color-scheme:dark){body{background:#0d1117;color:#e6edf3}}@media(prefers-color-scheme:light){body{background:#fff;color:#1f2328}}</style>\n'
M.mathjax_script = '<style>\nmjx-container[display="true"] {\n  margin: 1.2em 0 !important;\n  overflow-x: auto;\n}\nmjx-container svg {\n  max-width: 100%;\n}\n</style>\n<script>\nMathJax = {\n  tex: {\n    inlineMath: [[\'$\', \'$\'], [\'\\\\(\', \'\\\\)\']],\n    displayMath: [[\'$$\', \'$$\'], [\'\\\\[\', \'\\\\]\']],\n    processEscapes: true,\n    processEnvironments: true\n  },\n  svg: {\n    scale: 1.05,\n    fontCache: \'global\'\n  },\n  options: {\n    skipHtmlTags: [\'script\', \'noscript\', \'style\', \'textarea\', \'pre\']\n  }\n};\n</script>\n<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>\n'
M.mermaid_script = '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">\n<script type="module">\nimport mermaid from \'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs\';\nmermaid.initialize({ startOnLoad: false, securityLevel: \'loose\', flowchart: { htmlLabels: true } });\nawait mermaid.run();\n</script>\n'
M.pseudocode_script = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css">\n<script src="https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.js"></script>\n<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.css">\n<script src="https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.js"></script>\n<script>\ndocument.addEventListener(\'DOMContentLoaded\', function() {\n    pseudocode.renderClass("pseudocode");\n});\n</script>\n'
M.graphviz_script = '<script type="module">\nimport { instance } from "https://cdn.jsdelivr.net/npm/@viz-js/viz@3/lib/viz-standalone.mjs";\nconst viz = await instance();\ndocument.querySelectorAll(".graphviz-src").forEach(el => {\n    const dot = el.textContent;\n    const svg = viz.renderSVGElement(dot);\n    svg.style.maxWidth = "100%";\n    el.replaceWith(svg);\n});\n</script>\n'
M.d2_style = '<style>\n.d2-diagram svg { max-width: 100%; height: auto; }\n.d2-error { color: #d32f2f; background: #ffeef0; padding: 1em; border-radius: 4px; }\n</style>\n'
M.excalidraw_style = '<style>\n.excalidraw-diagram svg { max-width: 100%; height: auto; }\n.excalidraw-error { color: #d32f2f; background: #ffeef0; padding: 1em; border-radius: 4px; }\n</style>\n'
M.CALLOUT_STYLE = '<style>\n.callout{border-radius:4px;border-left:4px solid rgb(var(--callout-color,68,138,255));background-color:rgba(var(--callout-color,68,138,255),.08);padding:12px 16px;margin:16px 0}\n.callout>p:last-child{margin-bottom:0}.callout>p:first-of-type{margin-top:0}\n.callout-title{display:flex;align-items:center;gap:6px;font-weight:600;color:rgb(var(--callout-color,68,138,255));margin-bottom:8px}\n.callout-title:last-child{margin-bottom:0}\n.callout-title svg{flex-shrink:0}\n.callout-title-inner{flex-grow:1}\n.callout-fold{transition:transform .15s ease;margin-left:auto}\n.callout-foldable .callout-title{cursor:pointer;user-select:none}\n.callout.is-collapsed .callout-fold{transform:rotate(-90deg)}\n.callout.is-collapsed>:not(.callout-title){display:none}\n.callout-note{--callout-color:68,138,255}\n.callout-abstract{--callout-color:0,176,255}\n.callout-info{--callout-color:68,138,255}\n.callout-todo{--callout-color:68,138,255}\n.callout-tip{--callout-color:0,191,165}\n.callout-success{--callout-color:0,200,83}\n.callout-question{--callout-color:233,162,0}\n.callout-warning{--callout-color:255,145,0}\n.callout-failure{--callout-color:255,82,82}\n.callout-danger{--callout-color:255,23,68}\n.callout-bug{--callout-color:255,23,68}\n.callout-example{--callout-color:124,77,255}\n.callout-quote{--callout-color:158,158,158}\n@media(prefers-color-scheme:dark){.callout{background-color:rgba(var(--callout-color,68,138,255),.15)}}\n</style>\n'
M.CALLOUT_SCRIPT = '<script>\ndocument.addEventListener(\'DOMContentLoaded\',()=>{\ndocument.querySelectorAll(\'.callout-foldable .callout-title\').forEach(t=>{\nt.addEventListener(\'click\',()=>t.parentElement.classList.toggle(\'is-collapsed\'));\n});\n});\n</script>\n'

return M
